Repository muhdavi/laporan-practice-big-data, pull requests merged in 2022-12, with the labels that each got.

#47 Presensei 08-12-2022 a.n. M.IKHSAN
  laporan/MIkhsan.tex
Labels: presensi

#48 Presensei 08-12-2022 a.n. RIZKI
  laporan/RizkiIlhami.tex
Labels: presensi

#52 presensi 08 desember 2022 Cut Opy Mandalisa
  laporan/CutOpyMandalisa.tex
Labels: presensi

#53 presensi 09 Desember 2022, Taravia Fauzah
  gambar/akses-localhost-8088.png
  gambar/akses-localhost-9078.png
  gambar/comel.png
  gambar/hasil1.png
  gambar/hasil2.png
  gambar/hasil2_2.png
  gambar/output.png
  gambar/output1.png
  gambar/output1_1.png
  lab_notes.tex
  laporan/TaraviaFauzah.tex
Labels: laporan, presensi

#54 Presensi 09-12-2022 a.n. Resha Russita
  laporan/ReshaRussita.tex
Labels: presensi

#57 Presensi 09-12-2022 a.n Rizki
  laporan/RizkiIlhami.tex
Labels: presensi

#58 Presensi 9-12-2022 a.n. MUNAWIR
  laporan/MuhammadMunawir.tex
Labels: presensi

#59 Presensi 09 Desember 2022 a.n Zulfahmi
  laporan/Zulfahmi.tex
Labels: presensi

#60 Presensi 9-12-2022 a.n. Adjie
  laporan/AdjieYusmunandar.tex
Labels: presensi

#61 Presensi 09-12-2022 a.n. M.IKHSAN
  lab_notes.tex
  laporan/MIkhsan.tex
Labels: presensi

#62 presensi 09 desember 2022 salsabila irmanda
  laporan/SalsabilaIrmanda.tex
Labels: presensi

#63 Presesnsi 09-12-2022 a.n. Jihan Dwi Sarah
  gambar/Akses-web-browser-8088(Jihan).png
  gambar/Akses-web-browser-9870(Jihan).png
  gambar/Hadoop-version(Jihan).png
  gambar/Java-version(Jihan).png
  gambar/perintah-jps(jihan).png
  laporan/JihanDwiSarah.tex
Labels: laporan, presensi

#64 presensi 09 Desember 2022 cut opy
  laporan/CutOpyMandalisa.tex
Labels: presensi

#65 presensi 09-12-2022
  laporan/AdindaAwaliah.tex
Labels: presensi

#81 update sekolah dan alamat
  lab_notes.tex
  laporan/NurulAflah.tex
Labels: documentation

#83 arya 15 desember 2022 present
  lab_notes.tex
  laporan/AryaSaputra.tex
Labels: documentation

#84 update sekolah dan alamat
  lab_notes.tex
  laporan/FaizaYuwafiqi.tex
Labels: documentation

#77 Presensi 15-12-2022 an Jihan Dwi Sarah
  gambar/JihanDwiSarah/WordCount bawaan-Hadoop(jihan).png
  laporan/JihanDwiSarah.tex
Labels: laporan, presensi

#78 presensi 15-12-2022 a.n M.IKHSAN
  laporan/MIkhsan.tex
Labels: laporan, presensi

#79 Presensi 15-12-2022 a.n. Cut Opy Mandalisa
  laporan/CutOpyMandalisa.tex
Labels: presensi

#80 Presensi 15-12-2022 a.n. Munawir
  gambar/futura.jpeg
  laporan/MuhammadMunawir.tex
Labels: presensi

#82 presensi 15-12-2022 a.n Nurani Harum Fardaniah
  laporan/NuraniHarumFardaniah.tex
Labels: presensi

#85 15 desember 2022 a.n. adinda
  gambar/hasil instalasi apache hadoop.png
  laporan/AdindaAwaliah.tex
Labels: laporan, presensi

#72 presensi 15 Desember 2022 Taravia Fauzah
  lab_notes.tex
  laporan/TaraviaFauzah.tex
Labels: presensi

#73 Presensi 15-12-2022 a.n. Rauzatinur Syah
  laporan/RauzatinurSyah.tex
Labels: presensi

#74 Presensi 15-12-2022 an. Resha Russita
  laporan/ReshaRussita.tex
Labels: presensi

#75 presensi 15-12-2022 a.n Adjie
  lab_notes.tex
  laporan/AdjieYusmunandar.tex
Labels: presensi

#76 presensi 15-12-2022 a.n. Rizki
  laporan/RizkiIlhami.tex
Labels: presensi

#96 presensi 16-12-2022 a.n Nurani Harum Fardaniah
  gambar/NuraniHarumFardaniah/sparkversion.png
  laporan/NuraniHarumFardaniah.tex
Labels: laporan, presensi

#89 Presensi 16-12-2022 an. Resha Russita
  gambar/ReshaRussita/langkah5-resha.png
  laporan/ReshaRussita.tex
Labels: laporan, presensi

#99 presensi 16-12-2022 Cut opy mandalisa
  laporan/CutOpyMandalisa.tex
Labels: presensi

#98 16 Desember 2022 a.n. Adinda
  laporan/AdindaAwaliah.tex
Labels: laporan, presensi

#97 absensi jihan dwi sarah 16-12-2022
  laporan/JihanDwiSarah.tex
Labels: laporan, presensi

#95 presensi 16-12-2022 a.n M.IKHSAN dan laporan tgl 09-12-2022
  laporan/MIkhsan.tex
Labels: laporan, presensi

#94 Presensi Zulfahmi 16-12-2022 a.n Zulfahmi
  laporan/Zulfahmi.tex
Labels: presensi

#93 presensi 16-12-2022 a.n. Adjie Yusmunandar
  lab_notes.tex
  laporan/AdjieYusmunandar.tex
Labels: presensi

#92 Presensi 16-12-2022 an. Salsabila Irmanda
  gambar/SalsabilaIrmanda/installspark.PNG
  laporan/SalsabilaIrmanda.tex
Labels: laporan, presensi

#91 presensi 16-12-2022 a.n. Rizki
  laporan/RizkiIlhami.tex
Labels: presensi

#90 presensi 16-12-2022 a.n. Rauzatinur Syah
  laporan/RauzatinurSyah.tex
Labels: presensi

#86 Presensi Faiza Yuwafiqi 16 Des 2022
  laporan/FaizaYuwafiqi.tex
Labels: laporan, presensi

#100 laporan cut opy
  gambar/01.png
  gambar/02.png
  gambar/03.png
  gambar/04.png
  laporan/CutOpyMandalisa.tex
Labels: laporan

#102 Presensi 22 Desember 2022 a.n. jihan dwi sarah dan update laporan
  gambar/JihanDwiSarah/Instalasi-Spark(jihan).png
  gambar/JihanDwiSarah/WordCount bawaan-Hadoop(jihan).png
  gambar/JihanDwiSarah/WordCount-Java(jihan).png
  gambar/JihanDwiSarah/solusi-java-compile(jihan).jpg
  laporan/JihanDwiSarah.tex
Labels: laporan

#117 update sekolah dan alamat yang bantu Taravia
  lab_notes.tex
  laporan/SyarfaniAkbar.tex
Labels: documentation

#115 presensi 22 Desember 2022 a,n Nurul Aflah
  laporan/NurulAflah.tex
Labels: presensi

#114 Presensi 22-12-2022 a.n Zulfahmi
  laporan/Zulfahmi.tex
Labels: presensi

#113 presensi 22-12-2022 a.n. Adjie Yusmunandar
  package com.example.rythm.sqlitetutorial.java
Labels: presensi

#112 Presensi 22-12-2022 A.n MUNAWIR
  laporan/MuhammadMunawir.tex
Labels: presensi

#111 presensi 22-12-2022 a.n. Cut Opy Mandalisa
  laporan/CutOpyMandalisa.tex
Labels: presensi

#110 presensi dan laporan 22-12-2022 a.n Nurani Harum Fardaniah
  laporan/NuraniHarumFardaniah.tex
Labels: presensi

#109 Presensi 22 desember 2022 an. Salsabila Irmanda
  laporan/SalsabilaIrmanda.tex
Labels: presensi

#108 Presensi 22 Desember 2022 a.n. Jihan Dwi Sarah
  laporan/JihanDwiSarah.tex
Labels: presensi

#107 presensi 22-12-2022 a.n M.IKHSAN
  laporan/MIkhsan.tex
Labels: presensi

#106 presensi 22-12-2022 a.n. Rauzatinur Syah
  laporan/RauzatinurSyah.tex
Labels: presensi

#105 presensi 22 desember 2022 Taravia Fauzah
  laporan/TaraviaFauzah.tex
Labels: presensi

#104 Presensi 22-12-2022 an. Resha Russita
  laporan/ReshaRussita.tex
Labels: presensi

#103 presensi 22-12-2022 a.n. Rizki
  gambar/RizkiIlhami/Spark.png
  laporan/RizkiIlhami.tex
Labels: laporan, presensi

#128 Presensi 23-16-2022 an. Resha Russita
  laporan/ReshaRussita.tex
Labels: presensi

#127 Update Zulfahmi.tex
  laporan/Zulfahmi.tex
Labels: presensi

#126 presensi 22-12-22 dan 23-12-22 a.n. Adinda
  laporan/AdindaAwaliah.tex
Labels: presensi

#125 Presensi 23 Desember 2022 a.n. Jihan Dwi Sarah
  gambar/JihanDwiSarah/kendala-WordCountPython(jihan).PNG
  laporan/JihanDwiSarah.tex
Labels: presensi

#124 presensi 23-12-2022 a.n. Cut Opy Mandalisa
  laporan/CutOpyMandalisa.tex
Labels: presensi

#123 presensi tgl 23-12-2022 a.n. Rauzatinur Syah
  laporan/RauzatinurSyah.tex
Labels: presensi

#122 presensi 23 des 2022 an. salsabila irmanda
  laporan/SalsabilaIrmanda.tex
Labels: presensi

#121 presensi 23-12-2022 a.n Nurani Harum Fardaniah
  laporan/NuraniHarumFardaniah.tex
Labels: presensi

#120 presensi 23-12-2022 a.n M.IKHSAN
  laporan/MIkhsan.tex
Labels: presensi

#119 presensi 23-12-2022 a.n. Rizki
  laporan/RizkiIlhami.tex
Labels: presensi

#118 presensi 23 Desember 2022 Taravia Fauzah
  laporan/TaraviaFauzah.tex
Labels: presensi

#130 update laporan jihan wordcount python dan pyspark selesai
  gambar/JihanDwiSarah/WordCount-PySpark(jihan).png
  gambar/JihanDwiSarah/WordCount-Python(jihan).png
  gambar/JihanDwiSarah/WordCount-Python2(jihan).png
  gambar/JihanDwiSarah/kendala-menjalankan-hadoop-python(jihan).PNG
  gambar/JihanDwiSarah/program-local-python(jihan).png
  gambar/JihanDwiSarah/solusi-python(jihan).png
  gambar/JihanDwiSarah/solusi-python-poin-6(jihan).png
  laporan/JihanDwiSarah.tex
Labels: laporan

#131 laporan program WordCountPython dan WordCountPySpark
  gambar/TaraviaFauzah/clustering dengan PCA.png
  gambar/TaraviaFauzah/hasil WordCounPython1.png
  gambar/TaraviaFauzah/hasil WordCountPySpark1.png
  gambar/TaraviaFauzah/hasil WordCountPySpark2.png
  gambar/TaraviaFauzah/hasil WordCountPython2.png
  gambar/TaraviaFauzah/hasil clustering dengan PCA.png
  gambar/TaraviaFauzah/hasil import KMeans.png
  gambar/TaraviaFauzah/import KMeans.png
  gambar/TaraviaFauzah/import VectorAssembler.png
  gambar/TaraviaFauzah/load package dan load data.png
  gambar/TaraviaFauzah/model KMeans clustering.png
  laporan/TaraviaFauzah.tex
Labels: laporan

#132 update laporan Rizki
  gambar/RizkiIlhami/Hadoop Version.png
  gambar/RizkiIlhami/Hadoop Web.png
  laporan/RizkiIlhami.tex
Labels: laporan

#133 Laporan 23-12-2022 dan Laporan individu an. Resha Russita
  gambar/ReshaRussita/grafikclusterassignment.png
  gambar/ReshaRussita/grafikjumlahclusterdanhasilsilhouette.png
  gambar/ReshaRussita/langkah6dan7pyspark.jpg
  gambar/ReshaRussita/langkah8dan9python.jpg
  gambar/ReshaRussita/tabelciri.png
  gambar/ReshaRussita/tabelvektor.png
  laporan/ReshaRussita.tex
Labels: laporan

#134 laporan tgl 16 dan 22 Desember 2022 dan laporan individu a.n. Rauzatinur Syah
  gambar/RauzatinurSyah/Tgs-individu no 3_4.png
  gambar/RauzatinurSyah/Tgs-individu no 5 assembled_datashow.png
  gambar/RauzatinurSyah/Tgs-individu no 5 figure.png
  gambar/RauzatinurSyah/Tgs-individu no 6 figure.png
  gambar/RauzatinurSyah/no6 wordcount Pyspark.png
  gambar/RauzatinurSyah/no7 wordcount Pyspark.png
  gambar/RauzatinurSyah/no8 wordcount python.png
  gambar/RauzatinurSyah/no9 wordcount python.png
  gambar/RauzatinurSyah/penulisan dalam for.png
  laporan/RauzatinurSyah.tex
Labels: laporan

#135 update laporan Rizki
  gambar/RizkiIlhami/hadoop fs -cat.png
  gambar/RizkiIlhami/hadoop fs -ls.png
  laporan/RizkiIlhami.tex
Labels: laporan

#139 update laporan a.n. adinda
  gambar/AdindaAwaliah/jps.png
  gambar/AdindaAwaliah/konfigurasi apache hadoop web 8088.png
  gambar/AdindaAwaliah/konfigurasi apache hadoop web 9870.png
  laporan/AdindaAwaliah.tex
Labels: laporan

#138 laporan 1-12-2022 a.n NadzuraKumaira
  gambar/NadzuraKumaira/hadoop version.png
  laporan/NadzuraKumaira.tex
Labels: laporan

#137 Laporan 1-16 Desember 2022 a.n Faiza Yuwafiqi
  gambar/FaizaYuwafiqi/10 b.png
  gambar/FaizaYuwafiqi/6 dan 7 a.jpeg
  gambar/FaizaYuwafiqi/6 dan 7 b.jpeg
  gambar/FaizaYuwafiqi/9 dan 10 a.png
  gambar/FaizaYuwafiqi/jps.jpeg
  gambar/FaizaYuwafiqi/localhost8088.jpeg
  gambar/FaizaYuwafiqi/localhost9870.jpeg
  laporan/FaizaYuwafiqi.tex
Labels: laporan

#140 Update laporan "Gagal menjalankan wordcount python dan pyspark"
  gambar/RizkiIlhami/WordCount Hadoop -cat.png
  gambar/RizkiIlhami/WordCount Hadoop -ls.png
  gambar/RizkiIlhami/WordCount Java -cat.png
  gambar/RizkiIlhami/WordCount Java -ls.png
  laporan/RizkiIlhami.tex
Labels: laporan

#141 update laporan a.n Nurani Harum Fardaniah
  gambar/NuraniHarumFardaniah/kendala.jpg
  gambar/NuraniHarumFardaniah/pyspark6.jpeg
  gambar/NuraniHarumFardaniah/pyspark7a.jpeg
  gambar/NuraniHarumFardaniah/pyspark7b.jpeg
  laporan/NuraniHarumFardaniah.tex
Labels: laporan

#145 Laporan Individu Jihan Dwi Sarah Selesai
  gambar/JihanDwiSarah/Hasil-clustering-dengan-PCA(jihan).png
  gambar/JihanDwiSarah/Menentukan-nilai-K-dengan-silhouette(jihan).png
  gambar/JihanDwiSarah/Spark-df-show(jihan).png
  gambar/JihanDwiSarah/assembled-data-show(jihan).png
  laporan/JihanDwiSarah.tex
Labels: laporan

#144 laporan 16 s/d 23 desember 2022 (tugas individu) an Salsabila Irmanda
  gambar/SalsabilaIrmanda/cekhasil wordcount pyspark.PNG
  gambar/SalsabilaIrmanda/cekhasil wordcount python.PNG
  gambar/SalsabilaIrmanda/grafik1.PNG
  gambar/SalsabilaIrmanda/grafik2.PNG
  gambar/SalsabilaIrmanda/hasil1.PNG
  gambar/SalsabilaIrmanda/hasil2.PNG
  gambar/SalsabilaIrmanda/hasilwordcount pyspark.PNG
  gambar/SalsabilaIrmanda/hasilwordcount python.PNG
  laporan/SalsabilaIrmanda.tex
Labels: laporan

#143 Update laporan 'Wordcount python selesai dibuat'
  gambar/RizkiIlhami/WordCount python step 6.png
  gambar/RizkiIlhami/WordCount python step 7.png
  gambar/RizkiIlhami/WordCount python step 8.png
  gambar/RizkiIlhami/WordCount python step 9.png
  gambar/RizkiIlhami/jps.png
  laporan/RizkiIlhami.tex
Labels: laporan
